title: "Yusuf Alhelou"
url: "https://www.yusufalhelou.com"
baseurl: ""

og_image: "/assets/website/YusufAlhelouWebsiteBanner.png"
permalink: /:title/

plugins:
  - jekyll-sitemap 

defaults:
  - scope:
      path: "assets/**" 
    values:
      sitemap: false
  - scope:
      path: "_includes/**"
    values:
      sitemap: false
    - scope:
      path: "push/**"
    values:
      sitemap: false

sitemap:
  exclude:
    - /push/
    - /assets/ 
    - HBDYomna.html 
    - holo-card.html
    - json.html
